<?php
/**
 * Custom Floating Buy Button.
 * Copyright (C) 2018 butSource (http://butsource.com.br)
 *
 * This file included in ButSource/FloatingBuyButton is licensed under OSL 3.0
 *
 * http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * Please see LICENSE.txt for the full text of the OSL 3.0 license
 */

/**
 * @var $block \ButSource\FloatingBuyButton\Block\FloatingBuyButton
 */
// @codingStandardsIgnoreFile
?>
<?php $_product = $block->getProduct(); ?>

<?php if ($_product->isSaleable()): ?>
<div id="floating-buy-button" data-bind="scope:'floating-buy-button'">
    <div class="buy-button-toggle">
        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
        <span class="cs-font clever-icon-down"></span>
    </div>
    <div class="content-container page-main">
        <div class="buy-details">
            <div class="product-name">
                <h2 class="page-title">
                    <span itemprop="name"><?= $block->escapeHtml($_product->getName()); ?></span>
                </h2>
            </div>
            <div class="product-price">
                <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                    <div class="price-value"><?= $block->getProductPrice($_product) ?></div>
                    <meta itemprop="priceCurrency" content="<?= $block->getCurrency(); ?>">
                </div>
            </div>
        </div>
        <div class="buy-button">
            <div class="actions">
                <button type="button"
                        title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>"
                        class="action primary trigger-tocart">
                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "#floating-buy-button": {
        "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout(); ?>
    }
}
</script>
<?php endif; ?>