<?php
/**
 * @var \Magestat\FloatingBuyButton\Block\FloatingBuyButton $block
 * @codingStandardsIgnoreFile
 */

$_product = $block->getProduct();
?>
<?php if ($block->getIsEnabled() && $_product->isSaleable()): ?>
<div id="floating-buy-button" class="<?= $block->escapeHtml($block->getPosition()) ?>" data-bind="scope:'floating-buy-button'">
    <div class="buy-button-toggle">
        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
    </div>
    <div class="content-container page-main">
        <div class="buy-details">
            <div class="product-name">
                <h2 class="page-title" title="<?= $block->escapeHtml($_product->getName()) ?>">
                    <span itemprop="name"><?= $block->escapeHtml($_product->getName()) ?></span>
                </h2>
            </div>
            <div class="product-price">
                <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                    <div class="price-value"><?= $block->escapeHtml($block->getProductPrice($_product)) ?></div>
                    <meta itemprop="priceCurrency" content="<?= $block->escapeHtmlAttr($block->getCurrency()) ?>">
                </div>
            </div>
        </div>
        <div class="buy-button">
            <div class="actions">
                <button type="button"
                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                        class="action primary trigger-tocart">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "#floating-buy-button": {
        "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout(); ?>
    }
}
</script>
<?php endif; ?>
